 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api_users", type: :request do
  if Rails.env == 'test'
    Rails.application.routes.default_url_options[:host] = 'http://localhost:3000'
  end
  # APIUser. As you add validations to APIUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      APIUser.create! valid_attributes
      get '/api_users'
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      api_user = APIUser.create! valid_attributes
      get api_user_url(api_user)
      expect(response).to be_successful
    end
  end

#  describe "GET /new" do
#    it "renders a successful response" do
#      get new_api_user_url
#      expect(response).to be_successful
#    end
#  end

  describe "GET /edit" do
    it "render a successful response" do
      api_user = APIUser.create! valid_attributes
      get edit_api_user_url(api_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new APIUser" do
        expect {
          post api_users_url, params: { api_user: valid_attributes }
        }.to change(APIUser, :count).by(1)
      end

      it "redirects to the created api_user" do
        post api_users_url, params: { api_user: valid_attributes }
        expect(response).to redirect_to(api_user_url(APIUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new APIUser" do
        expect {
          post api_users_url, params: { api_user: invalid_attributes }
        }.to change(APIUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post api_users_url, params: { api_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested api_user" do
        api_user = APIUser.create! valid_attributes
        patch api_user_url(api_user), params: { api_user: new_attributes }
        api_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the api_user" do
        api_user = APIUser.create! valid_attributes
        patch api_user_url(api_user), params: { api_user: new_attributes }
        api_user.reload
        expect(response).to redirect_to(api_user_url(api_user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        api_user = APIUser.create! valid_attributes
        patch api_user_url(api_user), params: { api_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api_user" do
      api_user = APIUser.create! valid_attributes
      expect {
        delete api_user_url(api_user)
      }.to change(APIUser, :count).by(-1)
    end

    it "redirects to the api_users list" do
      api_user = APIUser.create! valid_attributes
      delete api_user_url(api_user)
      expect(response).to redirect_to(api_users_url)
    end
  end
end
