#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed_job/lib/delayed/command'
#require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
