# Migration to export translations from the database (translation_keys and translation_texts tables)
# to standard Rails I18n YAML files.
#
# This migration reads from the translation_keys and translation_texts tables and creates
# YAML locale files. It does NOT delete the database tables.
#
# Run with: rails db:migrate
#
class ExportTranslationsToYaml < ActiveRecord::Migration[6.1]
  def up
    export_translations_to_yaml_files
  end

  def down
    # This migration only exports data to files, no database changes to reverse
    Rails.logger.info "ExportTranslationsToYaml: down migration is a no-op (translation tables preserved)"
  end

  private

  def export_translations_to_yaml_files
    Rails.logger.info "Starting export of translations from database to YAML files..."

    # Get available locales from the database
    locales = execute("SELECT DISTINCT locale FROM translation_texts").to_a.map { |r| r['locale'] || r[0] }.compact
    locales = ['en', 'he', 'ru'] if locales.empty?

    locales.each do |locale|
      export_locale(locale)
    end

    Rails.logger.info "Translation export complete!"
  end

  def export_locale(locale)
    Rails.logger.info "Exporting translations for locale: #{locale}"

    translations = {}

    # Query all translations for this locale
    # Using ActiveRecord's quote to escape the locale parameter to prevent SQL injection
    escaped_locale = connection.quote(locale)
    results = execute(<<-SQL)
      SELECT tk.key, tt.text
      FROM translation_keys tk
      LEFT JOIN translation_texts tt ON tk.id = tt.translation_key_id AND tt.locale = #{escaped_locale}
      ORDER BY tk.key
    SQL

    results.each do |row|
      key = row['key'] || row[0]
      text = row['text'] || row[1]

      next if key.blank?

      # Convert gettext key to I18n key format
      i18n_key = convert_gettext_key_to_i18n_key(key)

      # Use the translated text, or the key itself as fallback (for English)
      value = text.present? ? text : (locale == 'en' ? extract_fallback_from_key(key) : nil)

      next if value.blank?

      # Set the nested hash value
      set_nested_value(translations, i18n_key, value)
    end

    # Write to YAML file
    write_yaml_file(locale, translations)
  end

  def convert_gettext_key_to_i18n_key(key)
    # Handle gettext scope separator (|)
    # "task event|Approve" -> "task_event.approve"
    # "user role|Editor" -> "user_role.editor"
    if key.include?('|')
      parts = key.split('|', 2)
      scope = parts[0].strip.downcase.gsub(/[^a-z0-9]+/, '_').gsub(/^_+|_+$/, '')
      text_part = parts[1].strip.downcase.gsub(/[^a-z0-9]+/, '_').gsub(/^_+|_+$/, '')
      "gettext.#{scope}.#{text_part}"
    else
      # Simple key - convert to snake_case and prefix with gettext namespace
      snake_key = key.strip.downcase.gsub(/[^a-z0-9]+/, '_').gsub(/^_+|_+$/, '')
      # Truncate very long keys
      snake_key = snake_key[0, 60] if snake_key.length > 60
      "gettext.#{snake_key}"
    end
  end

  def extract_fallback_from_key(key)
    # For gettext keys with | separator, use the part after |
    if key.include?('|')
      key.split('|', 2).last.strip
    else
      key.strip
    end
  end

  def set_nested_value(hash, dotted_key, value)
    keys = dotted_key.split('.')
    current = hash

    keys[0..-2].each do |k|
      current[k] ||= {}
      current = current[k]
    end

    current[keys.last] = value
  end

  def write_yaml_file(locale, translations)
    # Build the full translation hash with locale as root
    full_hash = { locale => translations }

    # Write to config/locales directory
    output_path = Rails.root.join('config', 'locales', "#{locale}_gettext.yml")

    File.open(output_path, 'w:UTF-8') do |file|
      file.write("# Translations exported from database (translation_keys/translation_texts tables)\n")
      file.write("# Generated by ExportTranslationsToYaml migration\n")
      file.write("# Date: #{Time.current}\n\n")
      file.write(YAML.dump(full_hash))
    end

    Rails.logger.info "  Wrote #{output_path}"
  end
end
